# Server settings
server:
  port: 80
# address: 127.0.0.1
spring:
  ##数据库连接信息
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oams
    username: root
    password: KDJl8W@^KG8l
    driver-class-name: com.mysql.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    resultSetLogEnabled: true
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    filters: stat,wall,log4j
    #    filters: wall
    #     通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    logSlowSql: true
  #模板引擎
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    check-template: false
    enabled: false
  resources: # 指定静态资源的路径
    static-locations: classpath:/static/,classpath:/views/
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
#mybatis:
#  实体类所做包
#  type-aliases-package: cn.dabaisk.boot.model
#  mapper.xml所在位置
#  mapper-locations: classpath*:/cn/dabaisk/boot/mapper/*.xml
#  cacheEnabled: true
mybatis-plus:
  mapper-locations: classpath*:cn/dabaisk/boot/mapper/xml/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.dabaisk.boot.model
#  typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    id-type: 3  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用


#pagehelper分页插件配置 此处是yml书写格式
#pagehelper:
#  autoDialect: true
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql